name: FB ADFRIENDFOLLOWFOLLOWING BOT

on:
  workflow_dispatch:

  #schedule:
   # - cron: "0 2 * * *"

jobs:
  run-addfriendfollowers:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # CACHE NPM + PUPPETEER
      - name: Cache npm + puppeteer
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            ~/.cache/puppeteer
            node_modules
          key: puppeteer-${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      # SWAP MEMORY
      - name: Setup Swap
        run: |
          sudo swapoff -a || true
          sudo rm -f /swapfile || true

          sudo dd if=/dev/zero of=/swapfile bs=1M count=4096
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile

          free -h

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Run addfriendfollowing Bot
        run: node dashboard/index.js addfriendfollowing

      - name: Upload recordings
        uses: actions/upload-artifact@v4
        with:
          name: recordings-addfriendfollowing
          path: recording_*.mp4
