name: FB Scraper + Recorder

on:
  workflow_dispatch:

permissions:
 contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      # install ffmpeg untuk recorder
      - name: Install FFmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      # jalankan scraper + recorder
      - name: Scrape Facebook Groups
        run: node dashboard/scrapegroups.js

      # upload video hasil recording
      - name: Upload Video Artifact
        uses: actions/upload-artifact@v4
        with:
          name: scrape-video
          path: video.mp4

      # commit hasil JSON
      - name: Commit Groups
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          git add docs/groups.json

          git diff --cached --quiet || git commit -m "Auto update groups"

          git push
