name: FB Scraper + Recorder

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      # CACHE CHROMIUM
      - name: Cache Puppeteer
        uses: actions/cache@v4
        with:
          path: ~/.cache/puppeteer
          key: puppeteer-${{ runner.os }}

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      # INSTALL CHROME CEPAT (bukan snap)
      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      # OPTIONAL SWAP
      - name: Add Swap Memory
        run: |
          sudo swapoff -a || true
          sudo rm -f /swapfile || true
          sudo fallocate -l 2G /swapfile
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile
          free -h

      - name: Scrape Facebook Groups
        run: node dashboard/scrapegroups.js
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
          PUPPETEER_EXECUTABLE_PATH: /usr/bin/google-chrome

      - name: Upload Video Artifact
        uses: actions/upload-artifact@v4
        with:
          name: scrape-video
          path: video.mp4

      - name: Commit Groups
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          git add docs/groups.json

          git diff --cached --quiet || git commit -m "Auto update groups"

          git push
